### ISSUE TITLE
check_end_game

### ISSUE THREAD

**Issue by MichelangeloConserva** [alsora/deep-briscola#9]
Before updating the master with self play we must update the check_end_game function

#### old one
```
    def check_end_game(self):
        ''' check if the game is ended'''
        return self.deck.end_deck
```
#### new onw
```
    def check_end_game(self):
        return len(self.players[0].hand) == 0
```

The game was thought to be finished 3 turns before it should have

**Comment by alsora** [comment]
In the master branch that's not a problem as it's checked only when there are no more cards in hand.

Keep playing is set to false when player.draw return false

https://github.com/alsora/deep-briscola/blob/master/environment.py#L109

However you are right as it's not correct. 

Best solution: 

1) remove keep playing variable
2) in play_episode() 
The while loop becomes
    while not game.check_end_game():
3) game.draw_step does not return anything 
4) player.draw does not return anything. It throws an error if len(hand) > 3 and maybe print a debug line if trying to draw when there are no cards. 
5) game.check_end_game checks 2 conditions 
 (end deck and no cards in hand of all players)
Note that if 1 player has cards and the other has no cards, the game is not ending
